name: Semver Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Create Semver Tags
        uses: simbo/action-semver-release-action@f77f66747dc75fc5f069e34545f908ee14299216 # v1
